spring:
  application:
    name: JWT Practice 
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_practice
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    jwt:
      secret-key: 883e807d7ee46bfd82464d697b0e6455d32b8406c6ee3a36e4a97de7ab976196
      # 1 day
      expiration: 86400000
      refresh-token:
        # 7 days
        expiration: 604800000

